### ISSUE TITLE
cannot open file 'CAFE_results/Gamma_clade_results.txt': No such file or directory

### ISSUE THREAD

**Issue by gdmdxl** [jeffersonfparil/compare_genomes#18]
I noticed that there was an error when performing the mission GENE_EXPANSION_CONTRACTION. I changed line 134 in the file assess_specific_genes.nf. Change $TREE to an absolute path or copy it to the SPECIFIC_GENES folder to keep 176 lines of code working properly. But I am not sure if this is a bug.

Hope to get your reply.

**Comment by jeffersonfparil** [comment]
Good catch! Can you make a PR request then I'll merge it so I can properly give you credit? Otherwise I can make the change myself. Cheers!

**Comment by gdmdxl** [comment]
Thank you very much for your reply.You can change it directly.
