### ISSUE TITLE
Improve documentation and debug Venn diagram plotting

### ISSUE THREAD

**Issue by jeffersonfparil** [jeffersonfparil/compare_genomes#3]
- Make sure underscore or space requirements in the species names are properly documented
- Add helpful hints to fix conflicts with dates and genotype distances in iqtree's tree building step
- The Venn diagram can accommodate a maximum of 5 species, add a config file specifying the species the user wants to include in the diagram

**Comment by AkshitaJain2709** [comment]
Can we add more than 5 species?

**Comment by jeffersonfparil** [comment]
Yes you can add more than 5 species but just be mindful that the summary plot may get overcrowded.

**Comment by AkshitaJain2709** [comment]
Thanks, looks very interesting, will give it a go.
