### ISSUE TITLE
Process `PLOT` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by papelypluma** [jeffersonfparil/compare_genomes#6]
Dear compare_genomes developers,

I'd like to seek for your help on the possible resolution of an error encountered while running the pipeline particularly at the "plot_tree_conex_venn_4DTv.nf". The log file says "cannot open file 'ORTHOGROUPS_SINGLE_GENE.NT.timetree.nex': No such file or directory" which could have likely led to "Process `PLOT` terminated with an error exit status (1)". Indeed, this *nex file is missing in the output. I was wondering if by any chance you would know how to address this issue. It appears that besides this step, all other steps were executed successfully with output files. Looking forward to your response! Thanks a lot!

**Comment by estolle** [comment]
Hi there.

We have the same problem. In our case the underlying problem happens to be in the orthofinder.nf part. After running orthofinder and Panther, some of the outputfiles from the julia scripts are not generated. Subsequently no single copy ottholog alignments and trees are ngenerated and that PLOT error appears. The test worked but our own data fails.
I am stuck a bit witj this error as there is not real error message etc.

**Comment by estolle** [comment]
further info from myproblem (which I think is the same as OP):

I think it fails here in the modules/orthofinder.nf line 139:
 julia !{projectDir}/../scripts/orthogroup_classification_gene_family_GO_terms.jl \
            ORTHOGROUPS/orthogroups.pthr \
            PantherHMM_17.0/Panther17.0_HMM_familyIDs.txt \
            all_orthogroups.tmp \
            ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups.GeneCount.tsv \
            ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups_UnassignedGenes.tsv \
            ORTHOGROUPS/orthogroups_gene_counts_families_go.out
    echo "Output:"
    echo "  (1/1) ORTHOGROUPS/orthogroups_gene_counts_families_go.out"

When I manually run it like this:
julia ../scripts/orthogroup_classification_gene_family_GO_terms.jl ORTHOGROUPS/orthogroups.pthr PantherHMM_17.0/Panther17.0_HMM_familyIDs.txt all_orthogroups.tmp ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups.GeneCount.tsv ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups_UnassignedGenes.tsv ORTHOGROUPS/orthogroups_gene_counts_families_go.out

I get this error (after processing bar goes up to 100% and another few seconds of processing time):
ERROR: LoadError: BoundsError: attempt to access 1-element Vector{String} at index [1:5]
Stacktrace:
[1] throw_boundserror(A::Vector{String}, I::Tuple{UnitRange{Int64}})
@ Base ./abstractarray.jl:703
[2] checkbounds @ ./abstractarray.jl:668 [inlined] 
[3] getindex(A::Vector{String}, I::UnitRange{Int64})
@ Base ./array.jl:930
[4] top-level scope
@ ~/virtualenvs/compare_genomes/scripts/orthogroup_classification_gene_family_GO_terms.jl:130
in expression starting at
~/virtualenvs/compare_genomes/scripts/orthogroup_classification_gene_family_GO_terms.jl:130


any ideas how to avoid/fix this?

**Comment by jeffersonfparil** [comment]
Sorry to hear that. We have tried to smooth out some of the possible errors with other datasets but there are bounds to be specific cases which we have not accounted for yet. 
- Are any of the input files of the Julia script (scripts/orthogroup_classification_gene_family_GO_terms.jl) empty? 

Sorry again if it's not working seamlessly on your side. We are looking into having the error messages more informative.

**Comment by papelypluma** [comment]
Hi @jeffersonfparil. thanks for your response. I checked the input files for the julia script, and I confirm that besides "all_orthogroups.tmp" (no way to check) all input files are not empty. I also noticed that the paths for the orthofinder result directory name is specified based on the date orthofinder generates it, although it is unlikely that the input directory is hardcoded in the script.

**Comment by jeffersonfparil** [comment]
@papelypluma oh for your specific problem timetree2 is most probably failing to build a timetree because of conflicts in the divergence times in ‘compare_genomes/config/dates.txt’. You need to remove divergence time estimates with low confidence based on the number of literature reports and dating studies. I hope this helps. 

P. S. I've added this common troubleshooting note in the published [paper](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.876) and will add it to the readme file now.

**Comment by papelypluma** [comment]
@jeffersonfparil thanks for these pointers! will try this one. hopefully it works.

**Comment by estolle** [comment]
Thanks for the rapid repsonse.

For the mentioned step using the julia script my inputfiles are all NOT empty. I also changed divergence times in the dates.txt , in a 4 species test I provide 2 divergence times, one -80mya - thats the outgroup species compared to the 3 other species (or a different calculation says -65mya) and one 57mya. I elimnated additional values and could try supplying only 1 estimate. 
I see the same error printed that the timetree.nex is missing , i.e. was not generated. Also the single-ortholog-genes.aln is empty (hence no tree/timetree), and thats coming from the orthofinder.nf step after the panther step. In the test dataset (Arabidopsis) two files are present in the ORTHOGROUPS folder, which are missing in my output:
orthogroups_gene_counts_families_go.out
orthogroups_summarised_gene_counts.csv

Here are the first few lines of the inputs into that julia script:

head ORTHOGROUPS/orthogroups.pthr
OG0016734:Partamona_ailyae|PartamonaAilyae_022214-T1 PTHR10000.orig.30.pir 7.3e-11
OG0016734:Partamona_ailyae|PartamonaAilyae_022534-T1 PTHR10000.orig.30.pir 1e-08
OG0000592:Partamona_ailyae|PartamonaAilyae_023666-T1 PTHR10000.orig.30.pir 1.1e-08

head PantherHMM_17.0/Panther17.0_HMM_familyIDs.txt
    PTHR31416       TRANSMEMBRANE PROTEIN 125
    PTHR47584       FAMILY NOT NAMED
    PTHR45830       SERPENTINE RECEPTOR, CLASS I    transmembrane signal receptor#PC00197
    PTHR39944       FAMILY NOT NAMED
    PTHR37516       SCA1 COMPLEX SCAFFOLD PROTEIN SCAA  small GTPase mediated signal    #GO:0007264;cellular response to stimulus#GO:0051716;positive regulation of Ras protein signal #GO:0046579;positive regulation of TOR signaling#GO:0032008;regulation of cellular process#GO:0050794;Ras protein signal transduction#GO:0007265;intracellular signal transduction#GO:0035556;regulation of intracellular signal transduction#GO:1902531;TOR signaling#GO:0031929

head all_orthogroups.tmp
OG0000000
OG0000001
OG0000002
OG0000003
OG0000004

head ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups.GeneCount.tsv
Orthogroup      Bombus_terrestris       Melipona_quadrifasciata Partamona_ailyae        Plebeja_droryana        Total
OG0000000       13      191     14      10      228
OG0000001       0       0       0       227     227
OG0000002       1       0       131     1       133
OG0000003       123     0       0       0       123
OG0000004       120     0       0       0       120
OG0000005       0       0       0       117     117

head ${DIR_ORTHOGROUPS}/Orthogroups/Orthogroups_UnassignedGenes.tsv
Orthogroup      Bombus_terrestris       Melipona_quadrifasciata Partamona_ailyae        Plebeja_droryana
OG0016910       Bombus_terrestris|BombusTerrestris_000015-T1
OG0016911       Bombus_terrestris|BombusTerrestris_000020-T1
OG0016912       Bombus_terrestris|BombusTerrestris_000024-T1

**Comment by jeffersonfparil** [comment]
Hi @estolle,
Thanks for the additional info. How many line does `ORTHOGROUPS/orthogroups.pthr` have? We expect `hmmsearch` to identify more than 5 hits across all your orthogroups using the PantherHMM protein family models. If `ORTHOGROUPS/orthogroups.pthr` is too small, you may need to increase the E-value [here](https://github.com/jeffersonfparil/compare_genomes/blob/776c0c5549871b3b00973860ab1c4622841333f6/modules/orthofinder.nf#L114C4-L114C63) from 0.0001 to 0.01 as seen in some guides. Hope that helps.

**Comment by estolle** [comment]
ORTHOGROUPS/orthogroups.pthr has 568883 lines, all_orthogroups.tmp has 41658
I would think its all correct more or less, in that Julia script something goes wrong which shows up in the line 130. 

Would it help to send you the inputfiles for that script?

Thanks for your help!

**Comment by jeffersonfparil** [comment]
Yes please send them to me and I'll inspect what's happening in the script.
Nothing obvious I can see on line 130. It's just a precompilation step of
one of the functions using a small subset of the hit list.

**Comment by papelypluma** [comment]
@jeffersonfparil unfortunately the error still persists after a few more attempts with your suggestion on the dates.txt

**Comment by jeffersonfparil** [comment]
Hi @papelypluma,
Timetree2 still fails to create `ORTHOGROUPS_SINGLE_GENE.NT.timetree.nex`?

**Comment by jeffersonfparil** [comment]
The main output plot requires the timetree as we are using the time estimates in million years on the x-axis. However, you can simply use the iqtree output (`ORTHOGROUPS_SINGLE_GENE.NT.iqtree`) to plot your tree separately, if TimeTree2 keeps failing to generate the tree. Also related to @estolle issue, are any of the following files empty?
- `ORTHOGROUPS/orthogroups_gene_counts_families_go.out`
- `ORTHOGROUPS/orthogroups.pthr`
- `ORTHOGROUPS/orthogroups_summarised_gene_counts.csv`

**Comment by papelypluma** [comment]
Hi @jeffersonfparil. I confirm that all 3 files are not empty. I'll share the input files for the julia script, but "all_orthogroups.tmp" is nowhere to be found. Is it because this is a temporary file?

**Comment by jeffersonfparil** [comment]
Hi @papelypluma,
Don't worry about that, orthofinder works for you then. Let's figure out the problem with iqtree's timetree. Are these files non-empty:
- `ORTHOGROUPS_SINGLE_GENE.NT.aln`
- `alignment_parition.NT.nex`

**Comment by papelypluma** [comment]
@jeffersonfparil ORTHOGROUPS_SINGLE_GENE.NT.aln is not empty, while the partition file alignment_parition.NT.nex appears also to be not empty.

> #nexus
> begin sets;
> charset OG0004315 = -;
> charset OG0004316 = -;
> charset OG0004317 = -;
> charset OG0004318 = -;
> charset OG0004319 = -;
> charset OG0004320 = -;
> charset OG0004321 = -;
> charset OG0004322 = -;
...
> charset OG0006870 = -;
> charset OG0006871 = -;
> charset OG0006872 = -;
> charset OG0006873 = -;
> charset OG0006874 = -;
> charset OG0006875 = -;
> charset OG0006876 = -;
> charset OG0006878 = -;
> charset OG0006879 = -;
> end;

**Comment by jeffersonfparil** [comment]
Yes, `alignment_parition.NT.nex` is missing the coordinates. Can you please comment-out lines 217-219 of `single_gene_orthogroups_tree.nf` and re-run it? Let's find out why the alignments per ortholog is not giving the alignment positions.

**Comment by jeffersonfparil** [comment]
Hi @estolle, thanks for sending those through. Can you also please send `ORTHOGROUPS/OrthoFinder/Results_<MMDD>/Orthogroups/Orthogroups.GeneCount.tsv`? I think I found the problem here and pushed a fix [here](https://github.com/jeffersonfparil/compare_genomes/blob/e9534138d53a2bd1e6f473f163e1a44628510476/scripts/orthogroup_classification_gene_family_GO_terms.jl#L35)

**Comment by estolle** [comment]
awesome! Thanks so much. This fix helped. This and the next julia scripts were running successfully now and produed the expected output. I am continuing with the next steps. Fingers crossed

ANother note. When rerunning multiple times, The Download of the large PANTHER Database always takes alot of time. Locally I modified the code to copy it over from a fixed location where I manually DL it.

Thanks so much and lets see if the rest runs smoothly =)

**Comment by jeffersonfparil** [comment]
That's great to hear. Let's see up to where it runs now.

> ANother note. When rerunning multiple times, The Download of the large PANTHER Database always takes alot of time. Locally I modified the code to copy it over from a fixed location where I manually DL it.

That's one of our pain points too when rerunning and I've been putting that on hold and that I just forget to fix it. I'll add a parameter on `config/params.config` to download or link the databases similar to the omics data download.

**Comment by papelypluma** [comment]
hi @jeffersonfparil thanks for th e pointers. i did comment out the lines you suggested while updating the julia files which had the fix, but that did not resolve the absence of *nex file though. the temporary files - that we're supposed to get for troubleshootig - didn't also appear this time in the output directory. i did see them before without updated julia script. let me re-run it again using the original file withot the fix and update asap.

**Comment by estolle** [comment]
> That's great to hear. Let's see up to where it runs now.
> 
> > ANother note. When rerunning multiple times, The Download of the large PANTHER Database always takes alot of time. Locally I modified the code to copy it over from a fixed location where I manually DL it.
> 
> That's one of our pain points too when rerunning and I've been putting that on hold and that I just forget to fix it. I'll add a parameter on `config/params.config` to download or link the databases similar to the omics data download.

great, this is v helpful!

Another few small things I encountered when running the pipeline step by step (at 4DTv step now):
one Orthogroup took very long in the macse alignment step - unclear why. I killed this process and the pipeline successfully continued (since this individual alignment step did not produce the alignment output it was simply missing in the next steps and not cuasing trouble). This is surely not a problem with the pipeline but with this particular alignment/sequence combination.
The second thing is during the 4DTv step. in the modules/ .nf file for it, there is and if then else statement in case the folder with .NT.cds files exists already (and hence the current run is a rerun). The step right afterwards however (julia script to concatenate the 4DTv.tmp files) assumes the 4DTv.tmp files to be in the working DIR and not in that alignment DIR where they are produced when rerun. I fixed it easily by adding a small mv command to move these files into the working DIR before that.

**Comment by papelypluma** [comment]
hi @jeffersonfparil. after uncommenting lines 217-219 in the `single_gene_orthogroups_tree.nf` script it gave a bunch of OG0000####*fasta files for each of the species and a combined file for all species, *-NT.aln files for each species and a `single_gene_list.geneNames` file. I confirm that all of them are non-empty.

**Comment by jeffersonfparil** [comment]
> > That's great to hear. Let's see up to where it runs now.
> > > ANother note. When rerunning multiple times, The Download of the large PANTHER Database always takes alot of time. Locally I modified the code to copy it over from a fixed location where I manually DL it.
> > 
> > 
> > That's one of our pain points too when rerunning and I've been putting that on hold and that I just forget to fix it. I'll add a parameter on `config/params.config` to download or link the databases similar to the omics data download.
> 
> great, this is v helpful!
> 
> Another few small things I encountered when running the pipeline step by step (at 4DTv step now): one Orthogroup took very long in the macse alignment step - unclear why. I killed this process and the pipeline successfully continued (since this individual alignment step did not produce the alignment output it was simply missing in the next steps and not cuasing trouble). This is surely not a problem with the pipeline but with this particular alignment/sequence combination. The second thing is during the 4DTv step. in the modules/ .nf file for it, there is and if then else statement in case the folder with .NT.cds files exists already (and hence the current run is a rerun). The step right afterwards however (julia script to concatenate the 4DTv.tmp files) assumes the 4DTv.tmp files to be in the working DIR and not in that alignment DIR where they are produced when rerun. I fixed it easily by adding a small mv command to move these files into the working DIR before that.

Hi @estolle ,
Good catch! I'll commit that change and cite you. Thanks! Let me know of other issues.

**Comment by jeffersonfparil** [comment]
> hi @jeffersonfparil thanks for th e pointers. i did comment out the lines you suggested while updating the julia files which had the fix, but that did not resolve the absence of *nex file though. the temporary files - that we're supposed to get for troubleshooting - didn't also appear this time in the output directory. i did see them before without using the updated julia script. let me re-run it again using the original file without the fix and update asap.

Hi @papelypluma,
Thanks for the persistence. Yes please share with me the output files. Also, is `alignment_parition.NT.nex` still missing the coordinates? Additionally, can you please take a look at the NextFlow error log files at `compare_genomes/work/<most_recent_folders>/<hash_signature>/.command.err`?

**Comment by papelypluma** [comment]
@jeffersonfparil thanks for your response! yes, coordinates are still missing. just shared output files with you. thanks!

**Comment by jeffersonfparil** [comment]
Hi @papelypluma,
I can't see anything wrong that jumps out from the files you've sent. Can you please send me the error logs from `compare_genomes/work/<most_recent_folders>/<hash_signature>/.command.err`? If you can send all the error logs from all the runs, that would be great. Thanks!

**Comment by jeffersonfparil** [comment]
Thanks for sending those through @papelypluma. By the way, what operating system are you running the workflow on?

**Comment by papelypluma** [comment]
@jeffersonfparil Thanks for looking into this! am using Ubuntu. 

> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04.3 LTS
> Release:        22.04
> Codename:       jammy

**Comment by jeffersonfparil** [comment]
> Ubuntu 22.04.3 LTS

Can you confirm that `bc` is installed because saw this error message:
`/expt/datboncan/tools/compare_genomes/work/4d/0739616dfd9a0df56ac5910ebcceea/.command.sh: line 15: bc: command not found`

**Comment by papelypluma** [comment]
@jeffersonfparil. indeed, it's not installed! let me re-run the pipeline this time with bc installed. will update how it goes.

**Comment by jeffersonfparil** [comment]
Hi @papelypluma, Thanks for confirming that. It's valuable info. I've update the conda environment yaml file to include `bc` and `grep` to the list of dependencies to install.

**Comment by papelypluma** [comment]
Thanks @jeffersonfparil! I confirm that following your suggestions has successfully addressed the problem. it's `bc `which had been missing from the very start that led to empty *nex "<start>-<end>" coordinates. One thing I noticed though is that updating the script `orthogroup_classification_gene_family_GO_terms.jl` with the most recent changes prevented me from running the pipeline successfully, so I had to stick with the original script prior to this issue. But in any case, all the changes/updates made have worked. Thanks a lot!

**Comment by jeffersonfparil** [comment]
Hi @papelypluma, that's good to hear. What was the error message from `orthogroup_classification_gene_family_GO_terms.jl`?

**Comment by papelypluma** [comment]
in my case *nt-aln* files were not generated, if I remember correctly. because L217-219 had an error not being able to remove non-existent files.

**Comment by jeffersonfparil** [comment]
> in my case _nt-aln_ files were not generated, if I remember correctly. because L217-219 had an error not being able to remove non-existent files.

That's all good then since the removal of the log file is at the end of the plotting Rscript: https://github.com/jeffersonfparil/compare_genomes/blob/1328583bcdc689b434d2d61be1096685adf76fef/scripts/plot_tree_singleGeneConex_venn_4DTv.R#L219.

Let me know if you have problems with `orthogroup_classification_gene_family_GO_terms.jl` in the future.

**Comment by gdmdxl** [comment]
I have meet same error. I find it is wrong when it run orthofinder in “Inferring gene and species trees”. The error is:



Inferring gene and species trees
--------------------------------

Traceback (most recent call last):
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/__main__.py", line 1778, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/orthologues.py", line 999, in OrthologuesWorkflow
    spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/orthologues.py", line 481, in RunAnalysis
    stag.Run_ForOrthoFinder(files.FileHandler.GetOGsTreeDir(), files.FileHandler.GetWorkingDirectory_Write(), self.ogSet.seqsInfo.speciesToUse, spTreeFN_ids)
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/stag.py", line 262, in Run_ForOrthoFinder
    ProcessTrees(dir_in, dir_matrices, dir_trees_out, gene_to_species, qVerbose=False, qForOF=True)
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/stag.py", line 191, in ProcessTrees
    t = tree.Tree(fn)
        ^^^^^^^^^^^^^
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'


I am trying fix it by “[ValueError: invalid mode: 'rU' #760](https://github.com/davidemms/OrthoFinder/issues/760)”. Hope it gets done smoothly！

**Comment by gdmdxl** [comment]
> I have meet same error. I find it is wrong when it run orthofinder in “Inferring gene and species trees”. The error is:
> 
> ## Inferring gene and species trees
> Traceback (most recent call last): File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/orthofinder", line 7, in main(args) File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/**main**.py", line 1778, in main GetOrthologues(speciesInfoObj, options, prog_caller) File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/**main**.py", line 1540, in GetOrthologues orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/orthologues.py", line 999, in OrthologuesWorkflow spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/orthologues.py", line 481, in RunAnalysis stag.Run_ForOrthoFinder(files.FileHandler.GetOGsTreeDir(), files.FileHandler.GetWorkingDirectory_Write(), self.ogSet.seqsInfo.speciesToUse, spTreeFN_ids) File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/stag.py", line 262, in Run_ForOrthoFinder ProcessTrees(dir_in, dir_matrices, dir_trees_out, gene_to_species, qVerbose=False, qForOF=True) File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/stag.py", line 191, in ProcessTrees t = tree.Tree(fn) ^^^^^^^^^^^^^ File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/tree.py", line 221, in **init** read_newick(newick, root_node = self, format=format) File "/home/lijiazheng/miniconda3/envs/compare_genomes/bin/scripts_of/newick.py", line 208, in read_newick nw = open(newick, 'rU').read() ^^^^^^^^^^^^^^^^^^ ValueError: invalid mode: 'rU'
> 
> I am trying fix it by “[ValueError: invalid mode: 'rU' #760](https://github.com/davidemms/OrthoFinder/issues/760)”. Hope it gets done smoothly！

orthofinder works without error！ compare_genomes still is running, but I think I fixed it.
